#!/usr/bin/python3

import json
import os.path
import sys
import time

from three_wolves.move_cube_env import RLPositionHistoryEnv
from stable_baselines3 import SAC

def main():
    # the goal is passed as JSON string
    # goal_json = sys.argv[1]
    # goal_trajectory = json.loads(goal_json)

    env = RLPositionHistoryEnv(goal_trajectory=None,
                               visualization=False)
    print(os.listdir('/userhome'))
    log_dir = '/userhome/best_model.zip'
    policy = SAC.load(log_dir)

    observation = env.reset()
    t = 0
    is_done = False
    while not is_done:
        action = policy.predict(observation)[0]
        observation, reward, is_done, info = env.step(action)
        t = info["time_index"]
        print("reward:", reward)


if __name__ == "__main__":
    main()
