#!/bin/sh

# run the script via `ros2 run` (for python scripts a simple symlink would also
# work but using `ros2 run` works for C++ executables as well)

# Examples for Stage 1
# ros2 run rrc_example_package real_move_up_and_down "$@"
# ros2 run three_wolves real_trajectory_example_with_gym "$@"
#ros2 run three_wolves real_trajectory "$@"
ros2 run three_wolves sim_trajectory "$@"

# Example for Stage 2
# ros2 run rrc_example_package dice_example_with_gym "$@"
